### ISSUE TITLE
Library

### ISSUE THREAD

**Issue by tipouic** [martinbudden/NRF24_RX#2]
Hi Martin,
Can you inclued the good library for this project because it have many library are named "NRF24" or can you use one file which fonction ([https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/master/Multiprotocol/NRF24l01_SPI.ino](url)

**Comment by martinbudden** [comment]
Sorry, I don't understand your question.

**Comment by tipouic** [comment]
I use the IDE Arduino and I have a error :

> In file included from RxSerialPrint.ino:1:0:
> D:\tipou\arduno\sketch\libraries\NRF24_RX\src/NRF24_RX.h:24:19: fatal error: NRF24.h: No such file or directory
>  #include <NRF24.h>

I have found 2 library which name "NRF24". Can youn inclued the good library or create a file which fonction inside

**Comment by martinbudden** [comment]
You need to include the library https://github.com/martinbudden/NRF24

**Comment by tipouic** [comment]
thank for the link but now, I have an other error which the "#include <SPI.h>" in serial sketch and the servo sketch are totaly bugged.
I use arduino IDE 1.6.5

**Comment by tipouic** [comment]
I have solve problem in my fork
